x-google-marketplace:
  schemaVersion: v2

  applicationApiVersion: v1beta1
  # The published version is required and MUST match the tag
  # of the deployer image
  publishedVersion: '24.4.1' #TAG of all images
  publishedVersionMetadata:
    releaseNote: >-
      A first release.
  # The images property will be filled in during part 2
  images:
    postgres_db:
      properties:
        postgresImage:
          type: FULL
    
    grafana:
      properties:
        grafanaImage:
          type: FULL    
          
    prometheus:
      properties:
        prometheusImage:
          type: FULL
    
    admin_service:
      properties:
        adminServiceImage:
          type: FULL
    
    prometheus-node-exporter:
      properties:
        prometheusNodeExporterImage:
          type: FULL
    
    fluent-bit:
      properties:
        fluentBitImage:
          type: FULL
    
    data_service:
      properties:
        dataServiceImage:
          type: FULL
    
    redis:
      properties:
        redisImage:
          type: FULL   
    
    envoy:
      properties:
        envoyImage:
          type: FULL    
    
    webapp:
      properties:
        webappImage:
          type: FULL    
    
    zookeeper:
      properties:
        zookeeperImage:
          type: FULL    
    
    clickhouse:
      properties:
        clickhouseImage:
          type: FULL    
    
    loki:
      properties:
        lokiImage:
          type: FULL    
    
    minio:
      properties:
        minioImage:
          type: FULL    
    
    rabbitmq:
      properties:
        rabbitmqImage:
          type: FULL

properties:

  hostName:
    type: string
    description: "Host name to be used with app deployment"      

  domain:
    type: string
    description: "Domain to be used with app deployment"

  grafanaAdminPassword:
    type: string
    default: "fiddler"
    description: "Password of grafana admin user."
    base64: True
    x-google-marketplace:
      type: MASKED_FIELD

  grafanaAdminUser:
    type: string
    default: "admin"
    description: "User of grafana admin."
    base64: True

  clickhouseRequestsCPU:
    type: string
    default: "8"
    description: "Clickhouse requested CPU value."

  clickhouseRequestsMemory:
    type: string
    default: "32Gi"
    description: "Clickhouse requested memory value."

  clickhouseLimitsCPU:
    type: string
    default: "8"
    description: "Clickhouse limits CPU value."

  clickhouseLimitsMemory:
    type: string
    default: "32Gi"
    description: "Clickhouse limits memory value."

  zookeeperRequestsCPU:
    type: string
    default: "1"
    description: "Zookeeper requested CPU value."

  zookeeperRequestsMemory:
    type: string
    default: "2Gi"
    description: "Zookeeper requested memory value."

  zookeeperLimitsCPU:
    type: string
    default: "1"
    description: "Zookeeper limits CPU value."

  zookeeperLimitsMemory:
    type: string
    default: "2Gi"
    description: "Zookeeper limits memory value."

  prometheusServerReplicas:
    type: integer
    default: 1
    description: "Prometheus replicas."

  minioClickhouseBackupHighAvailability:
    type: boolean
    default: false
    description: "Enable Minio highAvailability."

  minioRequestsCPU:
    type: string
    default: "1"
    description: "Minio requested CPU value."

  minioRequestsMemory:
    type: string
    default: "4Gi"
    description: "Minio requested memory value."

  minioLimitsCPU:
    type: string
    default: "2"
    description: "Minio limits CPU value."

  minioLimitsMemory:
    type: string
    default: "4Gi"
    description: "Minio limits memory value."

  postgresHost:
    type: string
    description: "IP address of CloudSql postgres instance"

  postgresUser:
    type: string
    description: "Database user name."

  postgresPassword:
    type: string
    description: "Database user password."
    base64: True
    x-google-marketplace:
      type: MASKED_FIELD

  name:
    type: string
    default: "fiddler"
    description: "Application name"
    x-google-marketplace:
      type: NAME

  namespace:
    type: string
    default: "default"
    description: "k8s namespace of where fiddler will be deployed"
    x-google-marketplace:
      type: NAMESPACE

required:
  - name
  - namespace
  - postgresHost
  - postgresUser
  - postgresPassword
  - hostName
  - domain